### PR TITLE
fix wrong package url

### LINKED ISSUE #1101: Wrong repositry url in package page
- https://www.npmjs.com/package/babel-runtime
repositry url: https://github.com/babel/babel/tree/master/packages/babel-runtime ✅ 
- https://cnpmjs.org/package/babel-runtime
repositry url: https://github.com/babel/babel/ ❌

### PR DESCRIPTION
**Pull request by ibigbug**
closed #1101

---
This change is [Reviewable](https://reviewable.io/reviews/cnpm/cnpmjs.org/1102)

### CODE REVIEW

File: controllers/web/package/show.js [hunk 1]
```diff
@@ -110,7 +110,7 @@ module.exports = function* show(next) {
     pkg.repository = null;
   }
   if (pkg.repository && pkg.repository.url) {
-    pkg.repository.weburl = giturl.parse(pkg.repository.url) || pkg.repository.url;
+    pkg.repository.weburl = /^https?:\/\//.test(pkg.repository.url) ? pkg.repository.url : (giturl.parse(pkg.repository.url) || pkg.repository.url);
```
Comment (fengmk2) [inline controllers/web/package/show.js]: add a test for this change

**Comment by fengmk2** [comment]
尼玛，测试用例完善到惊人。+1

**Comment by fengmk2** [comment]
2.19.1
